---
title: 비동기 복습
author:
  name: SsankQ
date: 2022-02-10 22:00:00 +0800
categories: [TIL, 2022-02]
tags: [TIL]
render_with_liquid: false
---

### 비동기(Asynchronous)

#### 동기 vs 비동기  

<img src='https://user-images.githubusercontent.com/89354370/153436168-72165e65-a638-46a6-b212-06e324523acc.png' width=400px height=300px alt='(A)sync' />
*이미지 출처: https://blog.metafor.kr/164*

- **동기(Synchronous)**  
: 순서대로 진행되는 여러 작업을 수행하게 될 때, 앞의 작업이 종료되고 나서야 다음 작업이 이어지게 되게끔 동작하는 방식

- **비동기(Asynchronous)**  
: 수행되어야 할 여러 작업들이 동시에 진행되게끔 동작하는 방식  

<br>
    *그럼 비동기로 요청하는 것은 똑같은 양의 작업을 수행하는 데 필요한 시간을 줄일 수 있는 건 알겠는데, 
    특정 작업을 진행하기 위해서 다른 작업의 결과물이 필수요소인 경우에는 어떻게 해야할까?*  
<br>
    *이렇듯, 비동기로 작업을 진행하는 동안 순서를 제어해주는 데 사용되는 방법들에는  
    **Callback**, **Promise**, **Async/Await** 이 대표적이다*

---

#### Callback

*함수가 인자로 다른 함수를 받아 실행되는 것을 뜻한다*

```jsx
const someFunction = (callback) => {
    console.log('안녕');
    callback()
}
someFunction(() => {
    console.log('하세요');
})

    /* 안녕
     * 하세요 */

/* 처음 선언된 함수가 호출될 때, '안녕'을 출력하게 되고,
 * 그런 다음 callback으로 전달된 무명함수가 실행되면서 '하세요'를 출력한다
 * 이렇듯 다른 함수를 인자로 받아 그 순서를 제어해주는 것이 Callback 함수이다 */
```

---

#### Promise

*Promise란 JavaScript 비동기 처리에 사용되는 객체를 뜻하며, 주로 `AJAX` 요청을 위한 기반으로 사용된다*

- **Promise 3가지 상태**
    - Pending  
    : 비동기 처리의 결과를 기다리고 있는 상태 
    - Fullfilled  
    : 비동기 처리가 정상적으로 완료되었고, 그 결과값을 갖고 있는 상태
    - Rejected  
    : 비동기 처리가 비정상적으로 끝난 상태

```jsx
const promiseFunction = new Promise((resolve, reject) => {
    // 내부에서 reject되는 경우와 resolve되는 경우를 다뤄준다
})

// Promise 객체는 then()을 통해 체이닝되는 형식으로 순서를 제어하여 데이터를 가공해준다
promiseFunction()
    .then((data) => console.log(data)) // fullfilled된 상태의 결과값(resolve)이 data에 담겨 전달된다
    .catch((err) => console.error(err)) // rejected 상태의 결과값(reject)이 err에 담겨 전달된다
```

---

#### async/await

*ES8에서 지원하는 함수로 더 간결하고 직관적으로 작성이 가능해 Promise 및 Callback Hell의 경우를 해소시켜줄 수 있다*

> *Callback*과 *Promise*의 경우는 에러 핸들링을 위한 기능이 제공되나  
> async/await은 자체적인 기능이 없어 `try/catch`로 에러를 핸들링할 수 있다

```jsx
const asyncFunction = async () => {
    // async await을 붙여서 사용함으로써 비동기 처리를 할 수 있게되고,
    // 동기적으로 처리하는 것과 같이 코드 가독성이 깔끔해지는 장점을 갖는다
    try {
        const someResult = await anotherFunction()
    
        console.log(someResult)
        console.log('정상 작동!')
        /* [anotherFunction의 결과값]
         * 정상 작동! */
    } catch(err) {
        console.error(err)
    }
    // try, catch로 예외처리하여 에러 핸들링을 할 수도 있다
}
```

#### 더 알아볼 내용

- Promise와 Async/await의 차이점  
> Promise는 테스트 케이스를 통과 못하지만, async/await은 통과하는 경우가 있었다 (물론 구현되는 내용에는 아무런 차이는 없었다)  

    *코드 가독성이나 에러 핸들링과 같이 코드 상으로 확인할 수 있는 부분 외적으로, 눈에 보이지 않는 추가적인 차이점이 있는지 찾아봐야겠다*